### ISSUE TITLE
PWA Implementation

### ISSUE THREAD

**Issue by abhisheknaiidu** [abhisheknaiidu/a-pop#2]

**Comment by Satyam1203** [comment]
Has somebody picked it up..? If  not, can I work on  this ?

**Comment by abhisheknaiidu** [comment]
Go Ahead @Satyam1203

**Comment by Satyam1203** [comment]
Is that serviceWorker.js written by you? It doesn't seem to be generated by CRA-template, also it is in .js extension but uses typescript. 

1. Should I overwrite that serviceWorker.js ?
2. Should it be in Typescript (.ts)?

**Comment by abhisheknaiidu** [comment]
> Is that serviceWorker.js written by you? It doesn't seem to be generated by CRA-template, also it is in .js extension but uses typescript.
> 
>     1. Should I overwrite that serviceWorker.js ?
> 
>     2. Should it be in Typescript (.ts)?
> 
> 
> I need to know the answers to these in order to proceed.

1. Yes you can overwrite it.
2. No, it should be in .js

**Comment by Satyam1203** [comment]
Hey @abhisheknaiidu , I'm getting score of following in Lighthouse, should I make a pull req. then ?

Fast and reliable - 2/3 ( -1 -> Slow page load)
Installable - 2/3 ( -1 -> Image url uses http instead of https)
PWA optimized - 4/8 (-4 -> other issues)

Those cut points can't be handled by me because I think you're fetching url from some API. 
Should I make a PR or not ?

**Comment by abhisheknaiidu** [comment]
@Satyam1203 Yup do for now, i'll figure out how to optimise after that.

**Comment by Satyam1203** [comment]
I've made a pull request. And just to tell you that in PRODUCTION, it is giving following score: 

Fast and reliable - 3/3 
Installable - 3/3
PWA optimized - 5/8 (-3 -> other issues)
